GET http://localhost:3000/heavy

### ping
GET http://localhost:80/ping

###
POST http://localhost:80/job-for-all
Content-Type: application/application/json

{
    "name":"esempio di job"
}

###
POST http://localhost:80/pdf
Content-Type: application/application/json

{
    "url":"https://www.google.com/"
}